import {BrowserRouter,Routes,Route,Link,useParams,useNavigate,useSearchParams} from 'react-router-dom';
import {createContext,useContext,useEffect,useState} from 'react';
import {Search,ShoppingCart,Menu,Truck,ShieldCheck,Headphones,Plus,Minus,Trash2,MessageCircle,ArrowRight,Check,X,CheckCircle2} from 'lucide-react';
import './cart-feedback.css';
import './checkout-success.css';

const pics=['photo-1586864387967-d02ef85d93e8','photo-1605600659908-0ef719419d41','photo-1570222094114-d054a817e56b','photo-1598511726623-d6a7501f7e5b','photo-1542838132-92c53300491e','photo-1556911220-bff31c812dba'];
const pic=x=>`https://images.unsplash.com/${x}?auto=format&fit=crop&w=900&q=85`;
const products=['Balanza electrónica comercial 40 kg','Selladora de impulso 30 cm','Licuadora industrial 2 litros','Cortadora de embutidos 10”','Empacadora al vacío profesional','Procesador de alimentos 6 L'].map((name,i)=>({id:i+1,slug:name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-'),name,category:['Balanzas','Selladoras','Gastronómicos','Cortadoras','Empacadoras','Procesadores'][i],price:[299,189,459,749,389,899][i],oldPrice:[349,229,0,829,0,999][i],image:i===3?'/products/cortadora-embutidos.png':pic(pics[i]),sku:`MV-00${i+1}`,bestseller:i===0||i===2||i===4}));
const C=createContext(),useCart=()=>useContext(C),money=n=>`S/ ${n.toFixed(2)}`;

function Provider({children}){const[items,set]=useState(()=>JSON.parse(localStorage.getItem('mv-cart')||'[]')),[notice,setNotice]=useState(null);useEffect(()=>localStorage.setItem('mv-cart',JSON.stringify(items)),[items]);useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(null),3500);return()=>clearTimeout(timer)},[notice]);const add=product=>{set(current=>current.some(item=>item.id===product.id)?current.map(item=>item.id===product.id?{...item,qty:item.qty+1}:item):[...current,{...product,qty:1}]);setNotice({product,key:Date.now()})};return <C.Provider value={{items,add,notice,dismissNotice:()=>setNotice(null),del:id=>set(items=>items.filter(item=>item.id!==id)),qty:(id,quantity)=>set(items=>items.map(item=>item.id===id?{...item,qty:Math.max(1,quantity)}:item)),total:items.reduce((sum,item)=>sum+item.price*item.qty,0)}}>{children}</C.Provider>}
function CartNotice(){const{notice,dismissNotice}=useCart();if(!notice)return null;return <div className="cart-notice" role="status"><span className="notice-check"><Check size={18}/></span><div><b>¡Agregado al carrito!</b><small>{notice.product.name}</small></div><Link to="/carrito" onClick={dismissNotice}>Ver carrito <ArrowRight size={16}/></Link><button onClick={dismissNotice} aria-label="Cerrar aviso"><X size={18}/></button></div>}
function FloatingCart(){const{items}=useCart(),[visible,setVisible]=useState(false);useEffect(()=>{const update=()=>setVisible(window.scrollY>180);update();window.addEventListener('scroll',update,{passive:true});return()=>window.removeEventListener('scroll',update)},[]);if(!visible)return null;return <Link className="floating-cart" to="/carrito" aria-label="Ver carrito"><ShoppingCart size={20}/><b>{items.reduce((sum,item)=>sum+item.qty,0)}</b></Link>}
function Header(){const{items,notice}=useCart(),nav=useNavigate(),[q,setQ]=useState('');return <><div className="top">RUC: 20615488896 <span>Tecnología Alemana</span><div><Link to="/nosotros">Nosotros</Link><Link to="/contacto">Contacto</Link><a href="https://wa.me/51976493676">WhatsApp</a></div></div><header><Link className="brand logo-brand" to="/"><img src="/logotiendaaa.png" alt="Maquinarias Versátil"/></Link><form className="search" onSubmit={e=>{e.preventDefault();nav('/tienda?q='+q)}}><input onChange={e=>setQ(e.target.value)} placeholder="¿Qué producto estás buscando?"/><button aria-label="Buscar"><Search/></button></form><Link className={'cart'+(notice?' cart-updated':'')} to="/carrito"><ShoppingCart/><b>{items.reduce((sum,item)=>sum+item.qty,0)}</b> Carrito</Link><Menu className="hamb"/></header><nav><Link to="/tienda">CATEGORÍAS</Link><Link to="/tienda?offer=1">OFERTAS</Link><Link to="/tienda?filter=bestseller">MÁS VENDIDOS</Link><Link to="/tienda?filter=new">NUEVOS</Link><Link to="/tienda?category=Balanzas">MAQUINARIA</Link><Link to="/tienda?category=Gastronómicos">EQUIPOS</Link></nav></>}
function AddButton({product,detail=false}){const{add,notice}=useCart(),added=notice?.product.id===product.id;return <button className={detail?'buy':''} onClick={()=>add(product)}><span className={added?'button-confirmed':''}>{added?<><Check size={16}/> AGREGADO</>:<><ShoppingCart size={16}/> {detail?'AGREGAR AL CARRITO':'AGREGAR'}</>}</span></button>}
function Card({p}){return <article className="card">{p.oldPrice>0&&<span className="sale">OFERTA</span>}{p.bestseller&&<span className="best">MÁS VENDIDO</span>}<Link to={'/producto/'+p.slug}><img src={p.image} alt={p.name}/></Link><div><small>{p.category}</small><Link to={'/producto/'+p.slug}><h3>{p.name}</h3></Link>{p.oldPrice>0&&<del>{money(p.oldPrice)}</del>}<strong>{money(p.price)}</strong><em>● Stock disponible</em><AddButton product={p}/></div></article>}
function Footer(){return <><section className="benefits">{[[Truck,'Envíos a todo el Perú'],[ShieldCheck,'Compra segura'],[Headphones,'Atención personalizada']].map(([I,t])=><div key={t}><I/><b>{t}<small>Siempre contigo</small></b></div>)}</section><footer><div className="brand logo-brand footer-logo"><img src="/logotiendaaa.png" alt="Maquinarias Versátil"/></div><div><h4>Categorías</h4>Balanzas<br/>Selladoras<br/>Equipos gastronómicos</div><div><h4>Contacto</h4>RUC 20615488896<br/>WhatsApp 976 493 676<br/>Tecnología Alemana</div><small>© 2026 Maquinarias Versátil. Todos los derechos reservados.</small></footer><a className="wa" href="https://wa.me/51976493676"><MessageCircle/></a></>}
function Wrap({children}){return <><Header/><main>{children}</main><Footer/></>};const Title=({children})=><div className="title"><h2>{children}</h2><Link to="/tienda">Ver todos <ArrowRight size={16}/></Link></div>;
function Home(){const cats=['Balanzas electrónicas','Selladoras','Empacadoras','Procesadores','Cortadoras','Equipos gastronómicos'];return <Wrap><section className="hero"><div><small>TECNOLOGÍA ALEMANA</small><h1>EQUIPOS PROFESIONALES<br/>PARA TU NEGOCIO</h1><p>Tecnología, potencia y rendimiento.</p><Link to="/tienda">VER PRODUCTOS <ArrowRight size={16}/></Link></div></section><Title>COMPRA POR CATEGORÍA</Title><section className="cats" id="categorias">{cats.map((x,i)=><Link to="/tienda" key={x}><img src={i===3?'/products/procesador-alimentos.png':pic(pics[i])} alt=""/><b>{x}</b><small>{i+4} productos</small></Link>)}</section><Title>PRODUCTOS DESTACADOS</Title><section className="grid">{products.map(p=><Card p={p} key={p.id}/>)}</section><section className="banner"><div><small>OFERTAS ESPECIALES</small><h2>Equipos que impulsan tu negocio</h2><p>Encuentra oportunidades en maquinaria seleccionada.</p><Link to="/tienda?offer=1">VER OFERTAS</Link></div></section><Title>LOS MÁS VENDIDOS</Title><section className="grid">{products.filter(p=>p.bestseller).map(p=><Card p={p} key={p.id}/>)}</section></Wrap>}
function Shop(){const[q]=useSearchParams(),term=q.get('q')?.toLowerCase()||'',mode=q.get('filter'),category=q.get('category'),categories=['Balanzas','Selladoras','Gastronómicos','Cortadoras','Empacadoras','Procesadores'],list=products.filter(p=>(!term||p.name.toLowerCase().includes(term))&&(!q.get('offer')||p.oldPrice)&&(!category||p.category===category)&&(!mode||mode==='new'||p.bestseller)),heading=q.get('offer')?'OFERTAS':mode==='bestseller'?'MÁS VENDIDOS':mode==='new'?'NUEVOS':category?category.toUpperCase():'TIENDA';return <Wrap><section className="shophead"><h1>{heading}</h1><p>Equipos y soluciones para hacer crecer tu negocio.</p><div className="shop-categories"><Link className={!category?'active':''} to="/tienda">Todas</Link>{categories.map(x=><Link className={category===x?'active':''} to={'/tienda?category='+x} key={x}>{x}</Link>)}</div></section><section className="shop"><aside><b>FILTRAR POR</b><hr/>Categoría<br/>{categories.map(x=><Link to={'/tienda?category='+x} key={x}>{x}</Link>)}<hr/>Rango de precio<input placeholder="Precio mínimo"/><input placeholder="Precio máximo"/></aside><div><div className="results">{list.length} productos encontrados <select><option>Ordenar por: Destacados</option></select></div><section className="grid">{list.map(p=><Card p={p} key={p.id}/>)}</section></div></section></Wrap>}
function Detail(){const{slug}=useParams(),p=products.find(x=>x.slug===slug)||products[0];return <Wrap><section className="detail"><img src={p.image} alt={p.name}/><div><small>{p.category} · SKU: {p.sku}</small><h1>{p.name}</h1><p className="stars">★★★★★ (12 reseñas)</p>{p.oldPrice>0&&<del>{money(p.oldPrice)}</del>}<h2>{money(p.price)}</h2><em>● Disponible en stock</em><p>Equipo profesional, confiable y listo para potenciar la productividad de tu negocio.</p><AddButton product={p} detail/><Link className="buy orange" to="/checkout">COMPRAR AHORA</Link><a className="consult" href="https://wa.me/51976493676">CONSULTAR POR WHATSAPP</a></div></section><section className="spec"><h2>Características técnicas</h2><p>Capacidad <b>Uso profesional</b></p><p>Material <b>Acero inoxidable</b></p><p>Garantía <b>12 meses</b></p></section></Wrap>}
function Cart(){const{items,del,qty,total}=useCart(),nav=useNavigate();return <Wrap><h1 className="page">TU CARRITO</h1><section className="cartpage"><div className="items">{items.length?items.map(i=><article key={i.id}><img src={i.image} alt=""/><b>{i.name}<small>{i.category}</small></b><strong>{money(i.price)}</strong><span><button onClick={()=>qty(i.id,i.qty-1)} aria-label="Reducir cantidad"><Minus/></button>{i.qty}<button onClick={()=>qty(i.id,i.qty+1)} aria-label="Aumentar cantidad"><Plus/></button></span><button onClick={()=>del(i.id)} aria-label="Eliminar producto"><Trash2/></button></article>):'Tu carrito está vacío.'}</div><Summary total={total} go={()=>nav('/checkout')}/></section></Wrap>}
function Summary({total,go}){return <aside className="summary"><h3>RESUMEN DEL PEDIDO</h3><p>Subtotal <b>{money(total)}</b></p><p>Envío <b>Por calcular</b></p><hr/><h2>Total <b>{money(total)}</b></h2><button onClick={go}>FINALIZAR COMPRA</button><a href="https://wa.me/51976493676">COMPRAR POR WHATSAPP</a></aside>}
function Checkout(){const{total,items}=useCart(),[order,setOrder]=useState(null),send=e=>{e.preventDefault();const data=new FormData(e.currentTarget),number=`MV-${Date.now().toString().slice(-6)}`,name=`${data.get('Nombre')} ${data.get('Apellidos')}`,lines=items.map(item=>`• ${item.name} x${item.qty} — ${money(item.price*item.qty)}`).join('\n'),message=`Hola, deseo confirmar mi pedido ${number}.\n\nCliente: ${name}\nTeléfono: ${data.get('Teléfono')}\nEntrega: ${data.get('entrega')}\nPago: ${data.get('pago')}\n\nProductos:\n${lines}\n\nTotal: ${money(total)}`;window.open(`https://wa.me/51976493676?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');setOrder({number,name})};return <Wrap><section className="checkout"><form onSubmit={send}><h1>FINALIZAR COMPRA</h1><h3>Datos de contacto</h3><div>{['Nombre','Apellidos','DNI / RUC','Teléfono','Correo electrónico','Departamento','Provincia','Distrito','Dirección','Referencia'].map(x=><label key={x}>{x}<input name={x} required/></label>)}</div><fieldset><legend>Método de entrega</legend><label><input type="radio" name="entrega" value="Recojo en tienda" defaultChecked/> Recojo en tienda</label><label><input type="radio" name="entrega" value="Delivery"/> Delivery</label><label><input type="radio" name="entrega" value="Envío a provincia"/> Envío a provincia</label></fieldset><fieldset><legend>Método de pago</legend><label><input type="radio" name="pago" value="Transferencia" defaultChecked/> Transferencia</label><label><input type="radio" name="pago" value="Yape / Plin"/> Yape / Plin</label><label><input type="radio" name="pago" value="Pago coordinado"/> Pago coordinado</label></fieldset><button type="submit">CONFIRMAR Y ENVIAR POR WHATSAPP</button></form><Summary total={total} go={()=>{}}/></section>{order&&<OrderSuccess order={order} onClose={()=>setOrder(null)}/>}</Wrap>}
function OrderSuccess({order,onClose}){return <div className="order-overlay" role="dialog" aria-modal="true" aria-labelledby="order-title"><section className="order-success"><button className="order-close" onClick={onClose} aria-label="Cerrar confirmación"><X size={20}/></button><CheckCircle2/><small>PEDIDO GENERADO</small><h2 id="order-title">¡Felicidades, {order.name.split(' ')[0]}!</h2><p>Tu pedido <b>{order.number}</b> fue generado correctamente. Abrimos WhatsApp para que puedas coordinarlo con nuestro equipo.</p><button onClick={onClose}>ENTENDIDO</button></section></div>}
function Info(){const{page}=useParams(),contact=page==='contacto';return <Wrap><section className="info"><small>MAQUINARIAS VERSÁTIL</small><h1>{contact?'HABLEMOS DE TU PROYECTO':'SOLUCIONES QUE HACEN CRECER NEGOCIOS'}</h1><p>Somos especialistas en maquinaria y equipos para negocios, emprendimientos y empresas. Ofrecemos tecnología, calidad y atención personalizada.</p><a className="buy" href="https://wa.me/51976493676">ESCRÍBENOS POR WHATSAPP</a></section></Wrap>}
export default function App(){return <BrowserRouter><Provider><Routes><Route path="/" element={<Home/>}/><Route path="/tienda" element={<Shop/>}/><Route path="/producto/:slug" element={<Detail/>}/><Route path="/carrito" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/:page" element={<Info/>}/></Routes><FloatingCart/><CartNotice/></Provider></BrowserRouter>}
